---

- name: find out uuid for target devices for fstab / crypttab
  command: "lsblk -nJ -o NAME,UUID,PARTUUID {{ _tgt_devices.keys()|join(' ') }}"
  register: _lsblk

- set_fact:
    _tmp: '{{ _lsblk.stdout|from_json }}'

- name: add uuid to _tgt_devices
  set_fact:
    _tgt_devices: >
      {{ _tgt_devices|combine({'/dev/' + item.name: _tgt_devices['/dev/'+ item.name]|default({})|combine({'uuid': item.uuid })}) }}
  with_items: "{{ _tmp['blockdevices'] }}"
  when: item.uuid is defined and _tgt_devices['/dev/' + item.name] is defined

- name: add uuid to _tgt_devices (device mapper)
  set_fact:
    _tgt_devices: >
      {{ _tgt_devices|combine({'/dev/mapper/' + item.name: _tgt_devices['/dev/mapper/'+ item.name]|default({})|combine({'uuid': item.uuid })}) }}
  with_items: "{{ _tmp['blockdevices'] }}"
  when: item.uuid is defined and _tgt_devices['/dev/mapper/' + item.name] is defined

- name: place templates in /etc
  template:
    src: "{{ item.src }}"
    dest: "{{ _tgt_root }}/etc/{{ item.dest|default(item.src) }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
  - { src: 'default/grub' }
  - { src: 'fstab' }
  - { src: 'crypttab', dest: 'crypttab' }

# In some configurations initramfstools will not correctly detect encrypted root, this
# forces cryptsetup to be included.
- name: enforce cryptsetup in initramfs
  copy:
    dest: "/etc/initramfs-tools/conf.d/cryptsetup"
    content: "export CRYPTSETUP=y"
  when: _luksopen.changed

- name: update initramfs
  command: chroot {{ _tgt_root }} update-initramfs -u -k all

- name: set up grub
  command: chroot {{ _tgt_root }} update-grub

- name: install boot loader (grub)
  command: chroot {{ _tgt_root }} grub-install {{ item['device'] }}
  with_items: "{{ layout }}"
  when: not item['skip_grub']|default(False)

- name: set root password
  command: >
      chroot {{ _tgt_root }} usermod -p '{{ root_password }}' root
  when: root_password is defined
