---

- name: Create filesystems
  command: >
    mkfs.{{ item.value.fs }}
    {{ item.value['mkfs_options']|default(dbstrp_mkfs_defaults[item.value.fs]|default('')) }}
    {% if 'label' in item.value %}
    {{ dbstrp_label_option[item.value.fs]|default('-L') }} {{ item.value.label[:dbstrp_label_max[item.value.fs]|default(16)] }}
    {% endif %}
    {{ item.key }}
  with_dict: "{{ _tgt_devices }}"
  when: >
    not item.value['encrypt']|default(False)
    and 'fs' in item.value
    and item.value['fs'] in ['ext4', 'xfs', 'vfat', 'f2fs']